services:
  dev_container:
    build:
      context: .
      dockerfile: Dockerfile.dev-container
    entrypoint: ./entrypoint.sh
    env_file: .env
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_APP_KEY: ${DD_APP_KEY}
      DD_DASHBOARD_ID: ${DD_DASHBOARD_ID}
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
      - ~/Projects:/workspace:cached
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
