services:
  dev_container:
    build:
      context: .
      dockerfile: Dockerfile.dev-container
    entrypoint: ./entrypoint.sh
    # customize as required, e.g.
    # env_file: .env
    # environment:
    #  FOO: bar
    # .config/gcloud maps my GCP credentials into my VS Code container
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
      - ~/Projects:/workspace:cached
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
