services:
  dev_container:
    build:
      context: .
      dockerfile: Dockerfile.dev-container
    entrypoint: ./entrypoint.sh
    # customize as necessary!  e.g.
    # env_file: .env
    # environment:
    #   FOO: "bar"
    #
    # Mac users might want to mount their .ssh dir, note that if you use UseKeychain
    # you might want to make your .ssh/config have the IgnoreUnknown option set:
    #
    # Host *
    #   IgnoreUnknown AddKeysToAgent,UseKeychain
    #   UseKeychain yes
    #
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
      - ~/.ssh:/root/.ssh
      - ~/Projects:/workspace:cached
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
